apiVersion: v1
kind: ConfigMap
metadata:
  name: syncservice-configmap
data:
  RABBIT_USER: {{ .Values.rabbitmq.auth.username }}
  RABBIT_PASSWORD: {{ .Values.rabbitmq.auth.password }}
  RABBIT_HOST: {{ .Values.rabbitmq.host }}
  RABBIT_EXCHANGE: {{ .Values.rabbitmq.exchange_name }}
  DB_HOST: {{ .Values.database.host }}:27017/?replicaSet=replicaset&authMechanism=DEFAULT&directConnection=true
  DB_USERNAME: {{ .Values.database.username }}
  DB_PASSWORD: {{ .Values.database.password }}
