env: private
html: private.html

microservices:
  - name: user
    image: ghcr.io/schnider94/user_service:latest
    port: 4001
    db:
      password: FOeD8FQRseRpc5i6JFHD4eUvupATpcHsE
      username: root
