apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker-registry-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Files.Get "files/docker_registry_auth.json" | b64enc }}
