apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conf-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if eq .Values.env "public" }}
    kubernetes.io/ingress.global-static-ip-name: conf-ip
{{- else }}
    kubernetes.io/ingress.class: public
{{- end }}
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  defaultBackend:
    service:
      name: conf-service
      port:
        number: 8000
  rules:
  - http:
      paths:
{{- range $v := .Values.microservices }}
      - path: /{{ $v.name }}
        pathType: Prefix
        backend:
          service:
            name: microservice-{{ $v.name }}-service
            port:
              number: {{ $v.port }}
    {{- if $v.extraPaths }}
      {{- range $path := $v.extraPaths }}
      - path: /{{ $path }}
        pathType: Prefix
        backend:
          service:
            name: microservice-{{ $v.name }}-service
            port:
              number: {{ $v.port }}
      {{- end }}
    {{- end }}
{{- end }}
