apiVersion: v1
kind: Service
metadata:
  name: conf-service
  namespace: {{ .Release.Namespace }}
{{- if eq .Values.env "public" }}
  annotations:
    cloud.google.com/backend-config: '{"default": "conf-backendconfig"}'
{{- end }}
spec:
  selector:
    app: conf
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
