apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: database
  ports:
    - name: database
      port: 27017
      targetPort: 27017
      protocol: TCP
