{{ if eq .Values.env "public" }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: microservices-backendconfig
spec:
  healthCheck:
    type: HTTP
    requestPath: /healthz
{{ end }}
