{{- range $v := .Values.microservices }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-{{ $v.name }}-deployment
  namespace: {{ $.Release.Namespace }}
  labels:
    app: microservice-{{ $v.name }}
spec:
  selector:
    matchLabels:
      app: microservice-{{ $v.name }}
  template:
    metadata:
      labels:
        app: microservice-{{ $v.name }}
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: {{ $v.name }}
        image: {{ $v.image }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
          name: microservice-{{ $v.name }}-configmap
        ports:
          - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4000
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4000
            scheme: HTTP
      - name: mongodb
        image: mongo
        imagePullPolicy: Always
        environment:
          MONGO_INITDB_ROOT_USERNAME: {{ $v.db.username }}
          MONGO_INITDB_ROOT_PASSWORD: {{ $v.db.password }}
          MONGO_INITDB_DATABASE: {{ $v.db.name }}
{{- end }}
