{{- range $v := .Values.microservices }}
---

apiVersion: v1
kind: Service
metadata:
  name: microservice-{{ $v.name }}-service
  namespace: {{ $.Release.Namespace }}
{{- if eq $.Values.env "public" }}
  annotations:
    cloud.google.com/backend-config: '{"default": "microservices-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
{{- end }}
spec:
  selector:
    app: microservice-{{ $v.name }}
  ports:
    - name: service
      port: {{ $v.port }}
      targetPort: 4000
      protocol: TCP
{{- end }}
