{{- range $v := .Values.microservices }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-{{ $v.name }}-deployment
  namespace: {{ $.Release.Namespace }}
  labels:
    app: microservice-{{ $v.name }}
spec:
  selector:
    matchLabels:
      app: microservice-{{ $v.name }}
  template:
    metadata:
      labels:
        app: microservice-{{ $v.name }}
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: {{ $v.name }}
        image: {{ $v.image }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: microservice-{{ $v.name }}-configmap
        ports:
          - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4000
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4000
            scheme: HTTP
      - name: mongodb
        image: bitnami/mongodb:4.4.15
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 27017
        env:
          - name: MONGODB_REPLICA_SET_MODE
            value: primary
          - name: MONGODB_REPLICA_SET_KEY
            value: replicasetkey123
          - name: MONGODB_ROOT_USER
            value: {{ $v.db.username }}
          - name: MONGODB_ROOT_PASSWORD
            value: {{ $v.db.password }}
          # - name: MONGODB_ADVERTISE_IP
          #   value: 127.0.0.1
        volumeMounts:
          - name: mongodb-keyfile
            mountPath: /etc/files
      volumes:
        - name: mongodb-keyfile
          secret:
            secretName: mongodb-keyfile-secret
            defaultMode: 0600
{{- end }}
