apiVersion: v1
kind: Service
metadata:
  name: owampd-service
  namespace: {{ $.Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: owampd
  ports:
    - name: owampd
      port: 861
      targetPort: 861
      protocol: TCP
{{- if eq .Values.env "private" }}
  externalIPs:
  - 192.168.178.30
{{- end }}
