{{ if .Values.testing.owamp }}
apiVersion: v1
kind: Service
metadata:
  name: owampd-service
  namespace: {{ $.Release.Namespace }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: owampd
  ports:
    - name: owampd
      port: 861
      targetPort: 861
      protocol: TCP
    - name: owamp-tcp-1
      port: 8760
      targetPort: 8760
      protocol: TCP
    - name: owamp-tcp-2
      port: 8761
      targetPort: 8761
      protocol: TCP
    - name: owamp-udp-1
      port: 8760
      targetPort: 8760
      protocol: UDP
    - name: owamp-udp-2
      port: 8761
      targetPort: 8761
      protocol: UDP
{{- if eq .Values.env "private" }}
  externalIPs:
  - 192.168.178.30
{{- end }}
{{ end }}
