{{ if .Values.testing.iperf }}
apiVersion: v1
kind: Service
metadata:
  name: iperf-service
  namespace: {{ $.Release.Namespace }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: iperf
  ports:
    - name: iperf-tcp
      port: 5201
      targetPort: 5201
      protocol: TCP
    - name: iperf-udp
      port: 5201
      targetPort: 5201
      protocol: UDP
{{- if eq .Values.env "private" }}
  externalIPs:
  - 192.168.178.30
{{- end }}
{{ end }}
