apiVersion: v1
kind: Service
metadata:
  name: iperf-service
  namespace: {{ $.Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: iperf
  ports:
    - name: iperf
      port: 5201
      targetPort: 5201
      protocol: TCP
{{- if eq .Values.env "private" }}
  externalIPs:
  - 192.168.178.30
{{- end }}
