apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: iperf
spec:
  selector:
    matchLabels:
      app: iperf
  template:
    metadata:
      labels:
        app: iperf
    spec:
      containers:
      - name: iperf3
        image: quay.io/networkstatic/iperf3
        args: ["-s"]
        ports:
        - containerPort: 5201
