on: [push]

permissions: write-all

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push user-service
        uses: docker/build-push-action@v3
        with:
          context: ./microservices/user-service
          push: true
          tags: ghcr.io/schnider94/user_service:latest
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}

      - name: Build and push conference-service
        uses: docker/build-push-action@v3
        with:
          context: ./microservices/conference-service
          push: true
          tags: ghcr.io/schnider94/conference_service:latest
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}

      - name: Build and push keynote-service
        uses: docker/build-push-action@v3
        with:
          context: ./microservices/keynote-service
          push: true
          tags: ghcr.io/schnider94/keynote_service:latest
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}

      - name: Build and push sync-service
        uses: docker/build-push-action@v3
        with:
          context: ./microservices/sync-service
          push: true
          tags: ghcr.io/schnider94/sync_service:latest
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}

      - name: Build and push app
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: ghcr.io/schnider94/app:latest
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}

      - name: Build and push owampd server
        uses: docker/build-push-action@v3
        with:
          context: ./owampd
          push: true
          tags: ghcr.io/schnider94/owampd-server:latest
